### ISSUE TITLE
Build a new package for 23.05

### ISSUE THREAD

**Issue by gaetronik** [maveonair/helix-ppa#4]
Hi,
thanks a lot for your packaging work.
Helix published a new version some weeks ago https://github.com/helix-editor/helix/releases/tag/23.05. Would you consider building a new package for this version ?

**Comment by maveonair** [comment]
It looks like something has changed again in the compilation of the grammars which fails the build now: https://launchpadlibrarian.net/670668290/buildlog_ubuntu-jammy-amd64.helix_23.05-1~ubuntu22.04~ppa1_BUILDING.txt.gz

Unfortunately, this happens every time a new version is released and I need to figure out why this is happening now with the latest release. Most of the time it happens because the build process wants to download something from the internet, and there is no internet access inside the launchpad agent during the build process....

**Comment by maveonair** [comment]
Please see https://github.com/helix-editor/helix/pull/7317

**Comment by maveonair** [comment]
@gaetronik With the help of the Helix community I could get the build working again (Changes: https://github.com/maveonair/helix-ppa/commit/cc5bf7082b170e7acea8ade224a5b2a909fede6e). I will test the 22.04 package and then trigger the build for 23.04 and 20.04.

**Comment by gaetronik** [comment]
Thanks a lot !
